Update python-package.yml

diff --git a/.github/workflows/python-package.yml b/.github/workflows/python-package.yml
--- a/.github/workflows/python-package.yml
+++ b/.github/workflows/python-package.yml
@@ -44,9 +44,9 @@ jobs:
       - name: Upload requirements.txt
         run: |
           # Make sure the requirements.txt is present in the repo
-          if [ ! -f requirements.txt ]; then
-            echo "requirements.txt not found!"
-            exit 1
+          #if [ ! -f requirements.txt ]; then
+            #echo "requirements.txt not found!"
+            #exit 1
           fi
           cat requirements.txt
           
